import Vue from 'vue'
import App from './App.vue'
import router from './router'
import store from './store/'
import Fragment from 'vue-fragment'
import OutsideClick from './directives/OutsideClick'
import { library } from '@fortawesome/fontawesome-svg-core'
import { 
  faInbox,
  faCalendar,
  faCalendarAlt,
  faStar,
  faCheck,
  faBars,
  faList,
  faPlus,
  faFolder,
  faFolderOpen,
  faEllipsisH,
  faBell,
  faBicycle,
  faBalanceScale,
  faBook,
  faBriefcase,
  faCalculator,
  faCamera,
  faCat,
  faChild,
  faCircle,
  faCrown,
  faCube,
  faDatabase,
  faDog,
  faDollarSign,
  faExclamation,
  faFeatherAlt,
  faFighterJet,
  faGlobe,
  faGraduationCap,
  faHeart,
  faKey,
  faLightbulb,
  faMarker,
  faLaptop,
  faKeyboard,
  faLayerGroup,
  faMapSigns,
  faPaperclip,
  faPause,
  faPlay,
  faPowerOff,
  faPhone,
  faRoad,
  faRobot,
  faRedo,
  faRocket,
  faRunning,
  faStop,
  faSave,
  faStarOfLife,
  faTabletAlt,
  faTasks,
  faTrophy,
  faTrashAlt,
  faTv,
  faTshirt,
  faThumbsUp,
  faThumbsDown,
  faWallet,
  faWeight,
  faUserSecret,
  faUser,
  faYinYang,
  faWrench
} from '@fortawesome/free-solid-svg-icons'
// import { faCalendar } from '@fortawesome/free-regular-svg-icons'
import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome'

library.add(
  faInbox,
  faCalendar,
  faCalendarAlt,
  faStar,
  faCheck,
  faBars,
  faList,
  faPlus,
  faFolder,
  faFolderOpen,
  faEllipsisH,
  faBell,
  faBicycle,
  faBalanceScale,
  faBook,
  faBriefcase,
  faCalculator,
  faCamera,
  faCat,
  faChild,
  faCircle,
  faCrown,
  faCube,
  faDatabase,
  faDog,
  faDollarSign,
  faExclamation,
  faFeatherAlt,
  faFighterJet,
  faGlobe,
  faGraduationCap,
  faHeart,
  faKey,
  faLightbulb,
  faMarker,
  faLaptop,
  faKeyboard,
  faLayerGroup,
  faMapSigns,
  faPaperclip,
  faPause,
  faPlay,
  faPowerOff,
  faPhone,
  faRoad,
  faRobot,
  faRedo,
  faRocket,
  faRunning,
  faStop,
  faSave,
  faStar,
  faStarOfLife,
  faTabletAlt,
  faTasks,
  faTrophy,
  faTrashAlt,
  faTv,
  faTshirt,
  faThumbsUp,
  faThumbsDown,
  faWallet,
  faWeight,
  faUserSecret,
  faUser,
  faYinYang,
  faWrench
)
Vue.component('font-awesome-icon', FontAwesomeIcon)

Vue.config.productionTip = false

Vue.directive('outside-click', OutsideClick)

Vue.use(Fragment.Plugin)

new Vue({
  router,
  store,
  render: h => h(App),
}).$mount('#app')
